### PR TITLE
feat: update wording in file sharing

### PR DESCRIPTION
**Pull request by acezard**

### CODE REVIEW

**Comment by zatteo** [comment]
Other languages still keep the `{{appname}}` version ?

**Comment by acezard** [comment]
> Other languages still keep the `{{appname}}` version ?

I check and they don't, updated all locales and remove variable injection in translation

**Comment by Ldoppea** [comment]
> > Other languages still keep the `{{appname}}` version ?
> 
> I check and they don't, updated all locales and remove variable injection in translation

Seems like you forgot the `mabulle/.../extra-es.json` and the `mabulle/.../extra-en.json`?

**Comment by acezard** [comment]
> > > Other languages still keep the `{{appname}}` version ?
> > 
> > 
> > I check and they don't, updated all locales and remove variable injection in translation
> 
> Seems like you forgot the `mabulle/.../extra-es.json` and the `mabulle/.../extra-en.json`?

updated ✅

**Review by Ldoppea — APPROVED** [review]

**Pull request merged**
