### PR TITLE
Add keep awake API

### PR DESCRIPTION
**Pull request by zatteo**
Add react-native-keep-awake and wrap it in a service. Tested on Android simulator and iOS device.

This API **works** when app is **in foreground** and **until app is quit**.

#### How to use it 

```
import {
  activateKeepAwake,
  deactivateKeepAwake
} from '/app/domain/sleep/services/sleep'


...

activateKeepAwake()

// long task where you do not want to go to sleep

deactivateKeepAwake()

...
```

#### Checklist

Before merging this PR, the following things must have been done:

* [ ] ~~Faithful integration of the mockups at all screen sizes~~
* [x] Tested on iOS
* [x] Tested on Android
* [x] Localized in English and French
* [ ] ~~All changes have test coverage~~
* [ ] ~~Updated README & CHANGELOG, if necessary~~

### CODE REVIEW

**Comment by Crash--** [comment]
Is it supported by all our targeted versions? No need of a new permissions?

**Comment by zatteo** [comment]
> Is it supported by all our targeted versions? No need of a new permissions?

Good question : 
- iOS > 8
- android minSdk = 16
- android compileSdk = 27

So everything seems fine.

No permissions needed.

**Comment by Crash--** [comment]
Another question @zatteo on this subject: 

Does this change is persisted accros reboot? If, for example, we disable sleep mode and forget / or not able to restore it (because of an app crash, for example), won't that cause the app to always block sleep mode on restart?

**Comment by zatteo** [comment]
If you go to background and foreground -> change is persisted, sleep timer is restarted when you go to foreground
If you quit and restart -> change is **not** persisted


For Android and iOS

**Comment by Crash--** [comment]
Thanks for the info.

> sleep timer is restarted when you go to foreground

What does that mean?

**Comment by zatteo** [comment]
If your iPhone is set up to go to sleep after 30s : 
- you start the app
- you do nothing for 30s
- then it goes to sleep

- you start the app
- you do nothing for 15s
- app goes to background
- app goes to foreground
- you do nothing for 30s 
- then it goes to sleep (whatever the 15s before which is common sense)

**Pull request merged**
