### PR TITLE
fix: add patches to make the build work on Android

### PR DESCRIPTION
**Pull request by acezard**
They have outdated or incompatible dependencies.
It is impossible for me to produce a build without these patches.
Should they be merged or locally used and ignored?

**react-native-keychain**
```
> Task :react-native-keychain:processDebugUnitTestManifest FAILED
/home/anc/cozy/cozy-react-native/node_modules/react-native-keychain/android/build/intermediates/tmp/manifest/test/debug/manifestMerger15350873941084906941.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/home/anc/cozy/cozy-react-native/node_modules/react-native-keychain/android/build/intermediates/tmp/manifest/test/debug/manifestMerger15350873941084906941.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/home/anc/cozy/cozy-react-native/node_modules/react-native-keychain/android/build/intermediates/tmp/manifest/test/debug/manifestMerger15350873941084906941.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

proposed fix (creates huge 11MB patch, not good):
```
-  testImplementation 'androidx.test:core:1.3.0-alpha03'
-  testImplementation "androidx.test:runner:1.3.0-alpha03"
-  testImplementation "androidx.test:monitor:1.3.0-alpha03"
+  testImplementation 'androidx.test:core:1.4.0'
+  testImplementation "androidx.test:runner:1.4.0"
+  testImplementation "androidx.test:monitor:1.4.0"
```

### CODE REVIEW

**Comment by Ldoppea** [comment]
For google safetynet we have this PR : https://github.com/cozy/cozy-react-native-google-safetynet/pull/4

I didn't merge it as a reminder as I didn't know how to deploy to NPM and then I forgot about it. Maybe we can take some time tomorrow to deploy it?

**Comment by Ldoppea** [comment]
For other libs we need to discuss about this. The patch files are way too heavy to understand what is happening inside.

And also I need to understand what is the impact on the release process. Today the build can be done with no problems (expect for the PR I linked in my previous message), so can you give more explanations about what is fixed by those patches?

**Comment by Ldoppea** [comment]
I just realized but navbar-height is not in the project anymore, so this part of the patch won't do anything.

**Comment by acezard** [comment]
> For google safetynet we have this PR : [cozy/cozy-react-native-google-safetynet#4](https://github.com/cozy/cozy-react-native-google-safetynet/pull/4). Same for navbar height: #475
> 
> I didn't merge it as a reminder as I didn't know how to deploy to NPM and then I forgot about it. Maybe we can take some time tomorrow to deploy it?

sorry I'm not sure what you mean by deploying to npm? My understanding is that we don't need to fork with patch-package, we have the modifications inside our repo.

I deleted navbar height as we don't use it anymore.

**Comment by acezard** [comment]
Let's talk about it while screen sharing when we can @Ldoppea

**Pull request closed without merging**
