### PR TITLE
fix: Force SDK version to 31 for react-native-android-navbar-height

### PR DESCRIPTION
**Pull request by Ldoppea**
This would fix the `AAPT: error: resource android:attr/lStar not found` error when building APK

___

TODO:

- [ ] Upgrade `cozy-react-native-google-safetynet` after cozy/cozy-react-native-google-safetynet#4 is merged

### CODE REVIEW

**Review by Crash-- — APPROVED** [review]

**Review by acezard — APPROVED** [review]

**Comment by acezard** [comment]
ping @Ldoppea

**Comment by Crash--** [comment]
@Ldoppea ping

**Comment by Crash--** [comment]
@Ldoppea can we close this PR?

**Comment by zatteo** [comment]
Closed because it is an old PR and we do not reproduce this issue anymore.

**Pull request closed without merging**
